global using System;
global using System.Collections.Generic;
global using System.Runtime.CompilerServices;
global using UnityEngine;
global using RWCustom;
global using MoreSlugcats;
global using JollyCoop;
global using JollyCoop.JollyMenu;
global using System.Reflection;
global using System.Diagnostics.CodeAnalysis;
global using BepInEx;
global using BepInEx.Logging;
global using Fisobs.Core;
global using Menu.Remix.MixedUI;
global using System.Security.Permissions;
global using System.Globalization;
global using System.Text.RegularExpressions;
global using static System.Reflection.BindingFlags;
global using Random = UnityEngine.Random;
global using MonoMod.RuntimeDetour;
global using MonoMod.Cil;
global using Mono.Cecil.Cil;
global using System.Linq;
global using HUD;
global using Color = UnityEngine.Color;
global using System.IO;
global using On.Menu;
global using Fisobs.Items;
global using Fisobs.Sandbox;
global using Fisobs.Properties;
global using SlugBase.DataTypes;
global using SlugBase.Features;
global using SlugBase;
global using LizardCosmetics;
global using OpCodes = Mono.Cecil.Cil.OpCodes;
global using Fisobs.Creatures;
global using DevInterface;
global using System.Reflection.Emit;
global using System.Runtime.ConstrainedExecution;
global using System.Net;
global using static Hailstorm.GlowSpiderState;
global using static Hailstorm.GlowSpiderState.Role;
global using static Hailstorm.GlowSpiderState.Behavior;
global using static Hailstorm.ObjectRelationship.Type;

[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]